# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.14.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout:
          post:
            - git fetch --all

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn install --freeze-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run tests!
      # lerna- run: yarn ci:test

      - run: git config --global user.email $GITHUB_EMAIL
      - run: git config --global user.name $GITHUB_USER

      # - setup_remote_docker:
      #     docker_layer_caching: true

      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="18.06.3-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin

      - run: echo 'export LAST_TAG=`git describe --abbrev=0 --tags`' >> $BASH_ENV
      - run: echo $LAST_TAG

      - run: yarn lerna run ci:deploy --since $LAST_TAG

      - run: yarn new-version
